server:
  port: 7860
  bind_address: "0.0.0.0"
  secret_key: "seek_secret_key_998877"

brand:
  title: "Seek"
  description: "My Private Metasearch Engine"

engines:
  - name: google
    engine: google
    active: true
  - name: bing
    engine: bing
    active: true
  - name: duckduckgo
    engine: duckduckgo
    active: true
  - name: wikipedia
    engine: wikipedia
    active: true

ui:
  default_locale: "en"
  query_in_title: true
  theme_args:
    simple:
      # কাস্টম সিএসএস ফাইলটি থিমের সাথে কানেক্ট করা
      custom_css: "themes/simple/css/custom.css"
